### ISSUE TITLE
Composable Content

### ISSUE THREAD

**Issue by dbaines** [katalyst/koi#309]
- Start Date: 2017-04-02
- Owner: DB
- Pull Request: https://github.com/katalyst/koi/pull/343
- Branch: https://github.com/katalyst/koi/tree/feature/composable-webpacker

# Summary

Provide an interface for users to compose content made of blocks of components.  

The end-goal is for a user to edit a page and be able to compose their page of all sorts of different components. They should be able to go to any page and add five paragraphs of WYSIWYG text, then add a table of latest positions that is automatically pulled from the careers module, then add some more WYSIWYG text beneath it. 

**This does not replace the CKEditor/Description field**, it instead should be able to live peacefully alongside it. 

This is a long one. 

![](https://media2.giphy.com/media/3o6Ztl5XZaXwjl6WEE/giphy.gif)

# Status

Work has begun on this feature and is available for testing in this branch: https://github.com/katalyst/koi/tree/feature/composable-webpacker

## Webpacker integration 

- [x] Rebased from master 8/6/2017
- [x] Add webpacker to test dummy app 
- [x] Update composable react components to use ES6 import/export/yarn/webpacker (koi 3+ is now a hard requirement) 

## Roadmap 

- [x] React interface for adding components and saving as a `jsonb` data type 
- [x] Create basic front-end partials for displaying the composable data 
- [x] Creating system for defining composable components addable in Koi at an application level 
- [x] Creating system for defining composable components addable in Koi at a model level 
- [x] Creating system for defining fallback sections based on component name 
- [ ] Creating system for defining custom field types in application 
- [x] Allow user to re-order composable components via drag-and-drop in Koi 
- [ ] Allow fields to flow next to each other 
- [x] Add webpacker generated files to the Koi generator (must be in-application to allow customisations rather than in-engine) 
- [ ] Update Ornament with basic styling for built-in components and containers  

## Field types

- [x] String
- [x] Text
- [x] Boolean
- [x] Checkboxes
- [x] Radios
- [x] Select
- [x] Rich Text (CKEditor)
- [x] Colour picker
- [x] Number 
- [x] Datepicker 
- [x] Range
- [ ] Image asset picker
- [ ] Document asset picker
- [ ] Longitude Latitude 
- [ ] Select2 - Single selection
- [ ] Select2 - Multiple select (tags) 

## Built-in Components

- [x] Section (should this be an opt-in config?)
- [x] Heading (2-6)
- [x] Text
- [x] CKEditor
- [ ] Tweet
- [ ] Image from asset manager 

## Built-in Sections

- [x] "Body" - all data is wrapped in a `.layout--container.composable-section__default` (default)
- [ ] Fullwidth - need to consider how this impacts multiple-column layouts, eg. sidebar navigation

# Motivation

This is often requested and we have implemented a system like in the past for a couple of websites. 
Having something in Koi to do this out of the box would be a massive win. 

Craft's Matrix fields are a pretty big inspiration for this. 

# Detailed design

## Glossary

**Composable**  
The composable field in it's entirity.  
Composables can have one-to-many components. 

**Component**  
You use the composable field to add components to your page.  
Components are made up of one-to-many fields.  
These appear in the "add" list and these are the things you can re-order, add or delete using the composable interface. 

**Section**
A method of grouping related composable components in to a container for front-end rendering.  
A section can have one-to-many components.  
Sections are optionally specified by the user, or can be ignored with no issues.  

**Field**  
A field lives in a component. These cannot be re-ordered in the interface. 

**Composable Data**  
This is the name of the JSON data that the composable creates and stores against the record.  

### Composable fields

`Composable` from a modelling point of view would just be a single `jsonb` field stored against the record. 

```
rails g migration AddComposableToPages composable_data:jsonb
```

Koi will automatically detect any fields named `composable_data` and treat it as a `composable` field type (much like `description` is treated as `rich_text` without needing to specify it)  

Once the field is added to the form fields list all you need to do is include the composable concern and away you go:  

```ruby
include Composable
```

This field can be added to any module, a page, a news_item or whatever module needs it.  

### Composable interface

The field would actually be rendered as a React component and provide to the user a way of adding, removing and re-ordering content blocks. 

As the user builds out their composable data it will feed the built-up JSON in to a hidden input field. When the user saves their form it will save the JSON against the record.  

The user will see a row of "Add" buttons where they can add their first component. 
The buttons will be autopopulated from a curated list of available components for the application (more on that later)  

![composable-add-new](https://cloud.githubusercontent.com/assets/685024/24579492/5779b518-173e-11e7-9d7b-51d593b2bfb5.PNG)

Clicking the add button will create a new component made up of one-to-many fields. Some examples:  

* "Heading" component would have "Heading text" as a text input and a "Heading size" as a drop-down select menu.  
* "Text" component would have just a single textarea  
* "Board Member" component would have several input fields for name, title, position, short description and an image 

As the user adds the components to their composable, they will see the form fields appear above the add tool:

![composable-added-section](https://cloud.githubusercontent.com/assets/685024/24579496/65994be0-173e-11e7-9dce-bc5ebb22d518.PNG)

Different components will have different groups of form fields:

![composable-fields](https://cloud.githubusercontent.com/assets/685024/24579501/7eae2330-173e-11e7-8e8a-360cce743b12.PNG)

Once the user is happy with their content, they hit save and the data is stored as JSON against the record. 

### Default components

The list of default components hasn't been considered yet, but for testing I've built:

* Section (single dropdown to define a section type)
* Heading (heading text and heading size)
* Text (single textarea)
* Kitchen Sink (testing component with a tonne of different fields in it to test all sorts of field configuration options)

Once this feature gets progressed to a good place we can look at thinking about what our smart defaults should be.  

### Sections

One of the many reasons this would be beneficial is creating content sections. 
Eg. In the style of LCA where the modules are made up of full-width containers but can have one-to-many components inside of it itself.  

Another example is having one large blue section that has some text, an image some more text and video.
Then there's a large green section that has some text and a video in it. 
These sections could be orderable themselves, but also the content inside of them could be orderable and customisable and can be transferred between the sections.

The way Craft deals with this is by having a `section` component that determines where a section starts. 
A lot of this implementation was heavily inspired by Craft.  

Sections are completely optional though. Not all sites will need it or take advantage of it. But for sites that don't need it, it's a bit silly to have that feature available or have the requirement of having a section. So to make it flexible I've implemented a method of falling back to a default section if none are made. 

Similarly, if the user creates a component outside of a section (but has other sections below) it again will treat those outside components as a default section. 

A simple way of thinking about it is **everything will be nested in a section**. Even if you don't define one. If you do define one it will use that, otherwise it will make one itself. 

### Fallback sections

@kippo raised the point that fallback sections could depend on the type of component added to the composable. 

For example you may have a video or banner component that should always appear full-width, it should fallback to a full-width section. However something like a couple of paragraphs of text should fallback to a container with padding and a max-width. 

This is handled in the `composable` concern and by default looks like this:

```ruby
def self.component_type_section_fallbacks
  {
    "video": "full_width",
    "full_banner": "full_width"
  }
end
```

It's a simple lookup object that is implemented like so:

```ruby
...
section_type: component_type_section_fallbacks[datum[:type]] || "body",
...
```

What this means is that it looks up the "type" of component it is to see if there is a fallback defined in the field_type_section_fallbacks object. If there is, it will use that, otherwise it will fallback to body. In this example if there is a component called video or full_banner it will fallback to a full_width section rather than the default of body. 

## Application-level customisation

Any application using composable probably won't want to use the defaults. We'll be building up composable components to add to the page per-application. Maybe we'll end up with some nice defaults, but odds are you'll want to customise it.  

There are two configuration options here:

1. Override the `composable.rb` concern file in the application 
2. Create settings in the `koi.rb` config file 

I'm leaning toward option 1, simply because the configuration for this thing can get pretty lengthy and would pollute the Koi config pretty quickly. All the out-of-the-box configuration is stored in the concern currently, so it's easy-as to simply override the file and start hacking away. 

### Defining your global components

The default global components are in the `composable.rb` concern file and look something like this:

```ruby
def self.component_types
  [{
    name: "Section",
    slug: "section",
    fields: [{
      label: "Section Type",
      name: "section_type",
      type: "select", 
      className: "form--auto",
      data: ["body", "fullwidth"] 
    }]
  },{
    ...
  }]
end
```

It's a pretty simple array of objects, the structure is like so:

```ruby
def self.component_types
  [{
    # The main component that appears in the "Add" list
    name: string, # Human-readable name of the component
    slug: string, # A unique slug/id for the component

    # The list of fields for this component
    fields: array [{ # An array of field objects
      label: string, # Human-readable field label
      name: string, # Field name 
      hint: string, # Hint message
      placeholder: string, # Placeholder
      type: string, # Field type (loads /javascripts/koi/react/Composable/ComposableField<type>.jsx)
      className: string, # Custom class for the field
      wrapperClass: string, # Custom class for the wrapper
      inputData: array, # An array of data attributes for the input field (eg. [{"thing": "yes"}] = <input data-thing="yes" />)
      inputAttributes: array, # Catch-all array of attributes and values to set directly on the input field (eg. [{"min": 10}] = <input min="10" />)
      data: array # Data for collections (check_boxes, radio_buttons, selects etc.), can be either flat array or array of objects of value/label pairs
    },{
      # Components can have multiple fields
    }]
  }]
end
```

There is a "Kitchen Sink" composable component in the `page` model that I'm using to demo all sorts of configuration options:

![composable-kitchen-sink](https://cloud.githubusercontent.com/assets/685024/24579518/e789bbd0-173e-11e7-9e2c-40688f089e49.PNG)

I'm planning on having a bunch of out-of-the-box field types.

These are the ones currently implemented:

* boolean
* check_boxes
* colour
* date
* number
* radio_buttons
* range
* rich_text
* select
* string
* textarea

I'm planning on adding image / document uploaders and taking a look at the current koi fields to see if there's any others that can be easily plugged in. 

### Validations

Currently I'm planning on using HTML5 validation techniques. It's not super widely supported but then again Koi is strictly latest version browsers anyway so I think for now it's good enough. 

You can use the catch-all `inputAttributes` array to set your validation rules.

Eg. A number field that is required and must be between 10 and 100:

```ruby
type: "number",
inputAttributes: [{required: true, min: 10, max: 100}]
```

***Note:*** For this I had to re-enable HTML5 validations in the `simple_form.rb` initialiser. I'm not sure why it's turned off, the commit for it simply says, "Generated Initialisers" and the docs say it should be enabled by default. Go figure. 

### Setting your components per model

The components that get passed in to the React component are `resource_class.component_types`, which means if you specify it on the model you can override the defaults specifically for a model.

In the future I'm thinking we store a global list (like what currently exists in the concern) and then instead of specifying the whole field data again for each model that needs them, instead specify a list of symbols much like the Koi config works for specifying form fields, index fields etc.

Something like this:

```ruby
# app/models/news_item
form fields: [:title, :composable_data],
     composables: [:heading, :rich_text]
```

This is future though, currently you need to create the whole `self.component_types` method on the model.  

### Fallback section customisation

You can override the fallback sections in the concern file by simply adding your fields and fallback sections to the lookup object:

```ruby
  def self.component_type_section_fallbacks
    {
      "video": "full_width",
      "full_banner": "full_width",
      "my_custom_component": "my_custom_section"
    }
  end
```

## Front-end rendering

Koi will take the sectioned data and assign it to the `composable_sections` attribute on your model. 
Eg: `@page.composable_sections`.

Each section has each of it's components as nested children so you can do something like this in the view:

```ruby
<%- @page.composable_sections.each do |section| -%>
  <div class="section__<%= section[:section_type] -%>">
    <%- section[:section_data].each do |component| -%>
      This is a <%= component["type"] -%>
    <%- end -%>
  </div>
<%- end -%>
```

This will loop over each section, and in turn loop over each component inside the section. 

From there you can pass the `type` in to a render call to render a partial based on the type of the component it is:

```ruby
<%= render "shared/composable_fields/#{component["type"]}", data: component -%>
```

So if you had a text component, this will render `shared/composable_fields/text`.
That way you can have a partial that will only be concerned with what a text type will render out. 
You could even have a `default` partial fallback incase you just want to render the data:

```ruby
<%= 
  begin
    render "shared/composable_fields/#{component["type"]}", data: component 
  rescue ActionView::MissingTemplate
    render "shared/composable_fields/default", data: component 
  end
-%>
```

So if you have a `colour` type but want it to be treated like `string` you could just have it fallback to `default` and have that just spit out the content regardless of what type it is.  

### Data sample

The React component will update a hidden input field with the JSON data as you update your fields.  

Here's an example of the kind of data it will generate (eg. `@page.composable_data`):

```json
[
  {
    "id": 1491357057789,
    "text": "This is a heading with no section defined, it will get a default \"body\" section.",
    "type": "heading",
    "heading_size": "1"
  },
  {
    "id": 1491357067513,
    "type": "section",
    "section_type": "body"
  },
  {
    "id": 1491357068989,
    "body": "This is some text in a body section. ",
    "type": "text"
  },
  {
    "id": 1491357075052,
    "body": "This is another text component in a body section. ",
    "type": "text"
  },
  {
    "id": 1491357087654,
    "type": "section",
    "section_type": "fullwidth"
  },
  {
    "id": 1491357109556,
    "text": "This is a heading three in a  fullwidth section. ",
    "type": "heading",
    "heading_size": "3"
  },
  {
    "id": 1491357090461,
    "body": "This is some text in a fullwidth section. ",
    "type": "text"
  }
]
```

To aid with front-end build, the sectioning and formatting will be done in ruby and will be exposed `@page.composable_sections` and will look something like this:

```json
[
  {
    "section_type": "body",
    "section_data": [
      {
        "id": 1491357057789,
        "text": "This is a heading with no section defined, it will get a default \"body\" section.",
        "type": "heading",
        "heading_size": "1"
      }
    ]
  },
  {
    "section_type": "body",
    "section_data": [
      {
        "id": 1491357068989,
        "body": "This is some text in a body section. ",
        "type": "text"
      },
      {
        "id": 1491357075052,
        "body": "This is another text component in a body section. ",
        "type": "text"
      }
    ]
  },
  {
    "section_type": "fullwidth",
    "section_data": [
      {
        "id": 1491357109556,
        "text": "This is a heading three in a  fullwidth section. ",
        "type": "heading",
        "heading_size": "3"
      },
      {
        "id": 1491357090461,
        "body": "This is some text in a fullwidth section. ",
        "type": "text"
      }
    ]
  }
]
```

### Available for testing

Feel free to checkout the branch above and have a play. It's implemented in the `page` model.  
Areas to note are:

```ruby
# the concern
/app/models/concerns/composable.rb
# a custom implementation on the page model
/app/models/page.rb
# view logic
/app/views/shared/_composables.html.erb
/app/views/shared/composable_fields
# javascript and react components
/app/assets/javascripts/koi/react/Composable
```

It's not ready for a pull request yet (and probably won't be any time soon) but it's a good technical proof of concept.  

If you have the react devtools installed watch the `data` prop on the main `Composable` component to see how the JSON is built up as you add/remove and edit your composable components. 

### Known issues

* Editing in the CKEditor source view doesn't save, but in WYSIWYG view it does save. This should be an easy yet annoying fix since according to the CKEditor docs, the WYSIWYG view and Source view have separate onChange() events. 
* CKEditors become unresponsive after being moved a couple times. 
* The method names won't match this RFC (eg. field_types instead of component_types), this will be fixed. This RFC is the source of truth regarding naming conventions. 

# Drawbacks

It's going to a take a long time and a lot of testing to make sure we can account for everything. I'm sure there's going to be new use-cases come up during development of an application that this won't account for and will probably be an evolving thing. 

There's no doubt that some sites we make might not even need this feature. 

If we have composable components that are data-driven in nature, such as the careers widget in the summary right up there at the top, I assume the data lookup will need to be in the view rather than the controller, since it can appear anywhere. 

Rendering partials is "slow". If we're looping over 20 components on one page that's 20 partials being rendered on the front-end. 

# Alternatives

Sticking with a WYSIWYG editor is only going to get us so far, and to be honest probably won't cut it for larger applications. We already do a lot of hard-coding for things that could be CMSable with a feature like this. 

# Unresolved questions

Should I look at switching to `react_on_rails` rather than `react-rails`? `react_on_rails` has webpack and yard integration while `react-rails` simply just renders `.jsx` files in to the asset pipeline. 
Using `react_on_rails` should theoretically make the move to `webpacker` in Rails 5.1 easier. 

Field types, customisation methods, best practices, documentation. 
What should our smart defaults be? Default components, default fallback sections, default partial views etc. 
Lots of questions. 

There seem to be a lot of issues with CKEditor when state changes that we'll need to workaround. Could be an opportunity to look in to a React editor alternative. 

Uploader - How are we going to get existing assets? (eg. on edit view)
Currently in the uploader partial we use `<%= Asset.find(value) -%>` to get the existing image. We could set up an end point to get the image via AJAX when uploader fields render, or we could somehow traverse the JSON for assets and throw them in a prop that gets sent to the React component. 

# The end

You made it to the end!

![](https://media2.giphy.com/media/3otPoS81loriI9sO8o/giphy.gif)

**Comment by Obversity** [comment]
> `include Composable`

This could be implemented similarly to Searchable and Slugged etc, i.e. `has_crud composable: true`

**Comment by jsidoryn** [comment]
Amazing work! Thanks for writing this up in so much detail. I've been having a look at Craft as well and this feature is pretty cool. 

My main question around this is if you have had any thoughts about urls & routes. Say we had a news items module. If you wanted to just show a list of news items, I'm assuming you'll just keep thinks as they are ie /news_items.

If you want to make it composable and allow a banner to be added, how would this work? Would you need to add a 'page' and then add a component for 'news item collection' and then 'banner' so you can then move these around the page. This would then likely have a different url structure such as /pages/news_items_list (not that it's a problem, just trying to flesh it out).

Or would you make the news_items module somehow composable. 

The first approach would lead to every url having a 'node' of some sort that content can then be added to. I'm keen for modules to use rails routes directly as for less CMS type sites (but that still require an admin) this would be a heavy overhead.

**Comment by dbaines** [comment]
Interesting question. I hadn't considered collection views at all in this. 

We could maybe add a composable as a setting to the NewsItem, much in the same way we would create a setting if they needed intro text for example. 

Any composable that's added to a collection view could get a special "collection" component that they can use to determine where the collection appears in line with everything else. This collection component would not be able to be deleted, but could be moved up and down and new components can be added around it.

**Comment by dbaines** [comment]
I've added data samples to the RFC to see how the data gets saved from the react client, and how it gets merged in to sections ready for front-end build.

**Comment by jsidoryn** [comment]
Here's a few clarifications after chatting with @dbaines that may be obvious but wasn't to me. 

The idea for this is that if adding to an existing model, it should be appended at the bottom. 

If it's for a 'page' then there may just be the title field with everything else composable. 

Another question is if there's a better way to handle validation. It's not great having two types of validation methods on the same form, client site with HTML 5 for composable content and rails validation for other fields. 

@Obversity @pvawser01 is there a way to hook into ActiveModel::Validations so these composable fields can be validated in the same way as other Rails records?

**Comment by Obversity** [comment]
@jsidoryn Not without quite a bit of effort, I'd guess, and we'd then need to push those errors to the react components, which would then need to deal with them. 

I get that inconsistency isn't great, but I don't see it as a huge deal, either.  

Worst case scenario, let's say a client doesn't fill in the title of the page, and doesn't fill in required fields in field types. They click submit, it instantly tells them the issue with the field types, they fix and click submit again, the page reloads with the error, they fill it in and it works. In other words, the worst case scenario is one extra step, but at the initial validations are instant. 

Best case scenario (but still with errors), they fill in all the required model fields, but fail to fill out some composable fields. They submit the form, and it tells them instantly what they got wrong, they fix and resubmit. In other words, in this best case scenario, they don't have to wait for a page reload to see errors.

**Comment by dbaines** [comment]
FYI regular simple form fields will also use HTML5 validations now that I've enabled it in the simple form initialiser, eg:

![screen shot 2017-04-05 at 2 58 39 pm](https://cloud.githubusercontent.com/assets/685024/24691067/78cc9cd8-1a10-11e7-9121-0ae1fbc21016.png)

**Comment by Obversity** [comment]
Does that effect the front-end as well?

**Comment by dbaines** [comment]
It does! As long as the front-end is using simple-form.  

You can disable it if it's getting in the way with [the `novalidate` attribute](https://www.w3schools.com/tags/att_form_novalidate.asp): 

```ruby
<%= simple_form_for(resource, html: { novalidate: true }) do |form| %>
```

**Comment by jsidoryn** [comment]
Ok, let's shelve the discussion on validations for the moment. I feel pretty strongly about validations working consistently for the user. I secretly love forms and this makes me feel uneasy. If it's just in the admin then the trade off might be worth it though. 

More investigation is needed but this is plenty for this RFC.

**Comment by Obversity** [comment]
It makes you feel uneasy because you've experienced it (mixed serverside/browser validations) before and it was a very bad user experience? Or because you *think* it'll feel bad? 

Personally, I feel like it's worth trialling before deciding it's bad.

**Comment by jsidoryn** [comment]
@Obversity you are more than welcome to put together a demo. like i said in the previous comment, i'm open to the chance that the trade off is worth it. 

i'm happy to take it offline if you'd like to talk more about user experience and forms. hit me up on wed if you'd like to chat more.

**Comment by dbaines** [comment]
Feature merged in to master
